name: boomsheets_dart
description: Boomsheets Dart over YES
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.3.4

dependencies:
  yes_parser:
    git:
      url: https://github.com/TheMaverickProgrammer/dart_yes_bindings.git
      ref: master

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
